# Basic HTTPS server configuration

[server]
address = 127.0.0.1
port    = 8080
threads = 8

# default root for static content
www_root = ./www

[ssl]
# true/false, yes/no, on/off, 1/0 are accepted
use_ssl = true

cert_file = certs/localhost.crt
key_file  = certs/localhost.key

[static]
# mount <url_prefix> <filesystem_path>
mount = /        ./www
mount = /assets/ ./www/assets
mount = /ui/     ./www/assets/ui
